name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: run unit tests
      id: run-unit-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: run unit tests
        setup-command: ''
        command: mvn -f ClosetLab/pom.xml -B -ntp -DfailIfNoTests=true test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN-UNIT-TESTS_RESULTS: "${{steps.run-unit-tests.outputs.result}}"
      with:
        runners: run-unit-tests
